version: "3"
services:
  postgres:
    build: ./postgres-db
    ports:
      - "5432:5432"
    restart: always

  frontend:
    build: ./flighter-frontend
    ports:
      - "3000:3000"
    restart: always

  backend:
    build: ./flighter-backend
    depends_on:
      - postgres
    ports:
      - "8090:8090"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/my_db
