version: "3"
services:
  postgres:
    build: ./postgres-db
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./development/.env

  frontend:
    build: ./flighter-frontend
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./development/.env
    volumes:
      - ./flighter-frontend/public/images:/flighter-frontend/public/images

  backend:
    build: ./flighter-backend
    depends_on:
      - postgres
    ports:
      - "8090:8090"
    restart: always
    env_file:
      - ./development/.env
    volumes:
      - ./flighter-frontend/public/images:/flighter-frontend/public/images
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/my_db

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   restart: always
  #   depends_on:
  #     - frontend
  #     - backend
