#Datasource Configuration
spring:
  datasource:
    hikari:
      maximum-pool-size: '4'
    username: 'poqwer95'
    password: '1234'
    url: 'jdbc:postgresql://localhost:5432/my_db'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        format_sql: true
    open-in-view: true

